### ISSUE TITLE
Check for version discrepancy when pushing image

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/full-builder#255]
## Background
In https://github.com/paketo-buildpacks/github-config/pull/302 we added a check when we push buildpackages to verify the buildpack version and the release tag. This is helpful since we manually cut releases, and the versions can easily get mismatched if we cut a minor or major release instead of a patch. Without this check, a buildpackage with mismatched versions might get pushed to Dockerhub which is less than ideal.

## Issue

Add a check for version discrepancy to the [push-image workflow](https://github.com/paketo-buildpacks/full-builder/blob/main/.github/workflows/push-image.yml), since we don't have this workflow in our common github-config repository.

**Comment by fg-j** [comment]
@sophiewigmore as far as I know, builder version isn't embedded in a builder's metadata, so there's not (currently) anything to check for this.

Try
```bash
docker pull paketobuildpacks/builder:full
docker image inspect paketobuildpacks/builder:full | jq -r '.[0].Config.Labels."io.buildpacks.builder.metadata"' | sed 's/\\\"/\"/g'  | jq .
```
to have a look at the pretty-printed builder metadata in the image labels.

Closing for now, but I am curious about whether builder version could be embedded in builder metadata. This could be useful in cases like https://github.com/paketo-buildpacks/builder/issues/53 where a user has a hard time determining which version of a builder they have because of the fixed image creation time.
