### ISSUE TITLE
Vulnerability on full-builder image (Ruby package) 

### ISSUE THREAD

**Issue by mehradn7** [paketo-buildpacks/full-builder#788]
Hello,

When building images with Paketo full-builder and NodeJS buildpack, the final image contains an old Ruby version with vulnerabilities.
Building with base-builder instead of full-builder does remove the Ruby libraries (and thus the vulnerabilities) but we need the full-builder to build our apps.

## Expected Behavior
The final image should not contain any vulnerability (especially with critical severity)

## Current Behavior
Critical VULNDB-255506 (closed-source vulnerability DB) is found when building an image with the following command:

`        pack build [image-name]:[image-tag] --buildpack gcr.io/paketo-buildpacks/nodejs --builder paketobuildpacks/builder:full --path [path-to-app-directory] `

We are building a nodeJS app but the builder:full image seems to include an old Ruby version (2.5.0) with vulnerabilities.

Here are the details regarding the vulnerability:

- **Vulnerable package**: rdoc - 6.0.1

- **Vulnerability description**: RDoc Gem for Ruby contains a flaw that is triggered as input to filenames is not properly sanitized before opening a file with kernel#open. With a specially crafted Ruby project containing a file with a filename that starts with '|' and ends with 'tags', a context-dependent attacker can inject and execute arbitrary commands.

- **Package path**: /usr/lib/ruby/gems/2.5.0/specifications/default/rdoc-6.0.1.gemspec

## Request

Could you provide a builder image with a more recent version of Ruby (and consequently rdoc) please?

Otherwise, could you suggest us a generic way of building images without embarking old frameworks/libraires that are prone to CVEs ?

Please don't hesitate to ask if more details are needed.

Thank you very much for your help, and have a nice day.

Regards,

**Comment by robdimsdale** [comment]
Hi @mehradn7 

You're correct in observing that the full-builder contains a version of Ruby that is vulnerable. I agree that we should fix that - either by updating `ruby` or removing it entirely. We're probably leaning towards the latter, as we expect users who require `ruby` to leverage the [Ruby Buildpack](https://github.com/paketo-buildpacks/ruby). We have plans to take a closer look at the full stack (and probably base stack too) to ensure unused packages (like ruby) are not included.

That being said, the Paketo full stack isn't really intended for production workloads. It's meant to provide everything that all applications might need in order to get up and running with Paketo buildapcks, and that necessarily means it contains more packages than any single application needs. This means that the surface area for vulnerabilities is large.

For production workloads, most consumers will create and manage their own stacks (and builders) tailored to their application's use-cases. We've recently improved the way we create stacks, so it's fairly easy to get started. Unfortunately we haven't updated the documentation yet, so I'll list the steps here:

1. Create a `stack.toml` and associated `Dockerfile`s for the Build and Run images in a directory.
    * You could look at existing stacks for inspiration e.g. [Jammy Base Stack](https://github.com/paketo-buildpacks/jammy-base-stack) 
1. Run `jam create-stack` against this directory
1. Create (or modify) an existing `builder.toml` to include the newly-created stack images
    * You could look at existing builders for inspiration e.g. [Jammy Base Builder](https://github.com/paketo-buildpacks/builder-jammy-base)
1. Run `pack builder create` against that `builder.toml`

Out of curiosity, if you're willing to share, what product or company are you working with that uses Paketo buildpacks in a production environment? We're always curious to learn more about adopters :)

**Comment by robdimsdale** [comment]
Also as an aside, we encourage consumers to migrate to the Ubuntu 2204 (Jammy) stacks/builders, as the 1804 (Bionic) stacks will be end-of-life in April 2023.

**Comment by fg-j** [comment]
💯 agree with what Rob's said here about use-cases for the full builder and creating your own stack/builder.

If you want to move to the jammy builder, it's here: https://github.com/paketo-buildpacks/builder-jammy-full. You can pull it from DockerHub here: https://hub.docker.com/r/paketobuildpacks/builder-jammy-full .

**Comment by mehradn7** [comment]
Thanks a lot for your swift answers @robdimsdale @fg-j,

Are there any compact "off the shelf" stacks/builders designed for the most usual types of apps (e.g. Java apps, NodeJS apps, ...) that we could reuse, or is building custom stacks/builders the only way to go ?

Regarding the security part, the following section of the documentation https://paketo.io/docs/concepts/stacks/#when-are-paketo-stacks-updated says

 _We aim to release stack updates that fix High and Critical CVEs within 48 hours of the patch release_

can we expect stacks (either base or full ones) to receive security updates (especially on Critical & High CVEs) accordingly to what is stated in this documentation, or is it more a best-effort remediation on your side ?

Thank you again for your help.

Regards,

**Comment by fg-j** [comment]
@robdimsdale has the affected package been patched in the full stack? @mehradn7 have you identified a next step that works for you? Trying to figure out what action is needed to close this out.

**Comment by robdimsdale** [comment]
No, the version of ruby in Bionic is still the version above: `6.0.1`:

```
 ❯ rg -i 'rdoc' bionic-full-stack-1.3.106-run-receipt.cyclonedx.json
45850:      "bom-ref": "pkg:gem/rdoc@6.0.1?package-id=331f4ee1b479f26e",
45853:      "name": "rdoc",
45862:      "cpe": "cpe:2.3:a:itoyanagi-sakura:rdoc:6.0.1:*:*:*:*:*:*:*",
45863:      "purl": "pkg:gem/rdoc@6.0.1",
```

This isn't likely to be fixed because the upstream version of the `ruby` package in Bionic does not appear to be getting updated by Canonical.

The real fix is probably to remove the packages from the full stack. I've opened issues on the [bionic](https://github.com/paketo-buildpacks/bionic-full-stack/issues/68) and [jammy](https://github.com/paketo-buildpacks/jammy-full-stack/issues/44) stacks to remove unused packages like ruby.

**Comment by fg-j** [comment]
Great! Thanks @robdimsdale. Given that this will need to be remediated at the stack level, I'm going to close this issue as "Not Planned".
